data:
  name: pubmed
  dataset_path: data/dataset
  partition_path: data/part_data
  num_feats: 500
  num_classes: 3
  is_multilabel: false
model:
  num_layers: 2
  hidden_dim: 512
  dropout_rate: 0.5
  use_norm: false
  aggregator_type: mean # default setting for graphsage
runtime:
  model_name: gcn
  learning_rate: 0.01
  weight_decay: 0
  num_epoches: 500
  mode: AdaQP2
  assign_scheme: adaptive
  exp_path: exp
  logger_level: INFO
  log_steps: 1
assignment:
  assign_cycle: 100
  profile_data_length: 200 
  group_size: 100
  coe_lambda: 0.5
  assign_bits: 8 # default uniform bits for quantization when no traced data is collected
